language: groovy
jdk:
- openjdk8
before_install:
- chmod +x gradlew

sudo: false

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
   